baseURL: "https://www.zainnasir.com/"
title: Zain Nasir
paginate: 7
theme: ["PaperMod"]

enableRobotsTXT: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: Zain Nasir
    description: "Software Developer & Researcher based in New York."
    author: Zain Nasir
    DateFormat: "Jan 2, 2006"
    defaultTheme: auto
    disableThemeToggle: true

    ShowReadingTime: true
    ShowWordCount: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    ShowBreadCrumbs: false
    ShowPageNums: true
    hidemeta: false
    showtoc: true
    tocopen: false
    hideAuthor: true

    assets:
        favicon: "/favicon.ico"
        disableHLJS: false

    homeInfoParams:
        Title: "\U0001F44B Hi, welcome to my blog."
        Content: "I am a software developer and researcher currently completing my Masters in Computer Science (AI Track) from Binghamton University. My expertise include autonomous navigation systems in drones, computer vision, and machine learning."
        Research: "My current [research](/research) involves optimizing edge-based SLAM techniques and tailoring them for deployment on small drones with limited compute power."
        Contact: "I am searching for full-time software development and machine learning engineer positions. If you are interested, check out my [resume](/resume.pdf)."
        Profile: "/profile.png"

    # Social Icons
    socialIconsStrokeWidth: 1.5
    socialIcons:
        - name: email
          url: "mailto:znasir1@binghamton.edu"
        - name: linkedin
          url: "https://www.linkedin.com/in/zainasir"
        - name: github
          url: "https://www.github.com/zainasir"
        - name: cv
          url: "/resume.pdf"

    # Search
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
        keys: ["title", "permalink", "summary", "content"]

    # Katex
    math: true

# Emoji
enableEmoji: true

# Navigation menu
menu:
    main:
        - name: Home
          url: /
          weight: 10
        - name: Blog
          pageRef: /blog
          weight: 20
        - name: Projects
          pageRef: /projects
          weight: 30
        - name: Research
          pageRef: /research
          weight: 40
        - name: Search
          pageRef: /search
          weight: 50

# Search
outputs:
    home:
        - HTML
        - RSS
        - JSON

# Disable default taxonomies
disableKinds:
    - taxonomy
