baseURL: "https://www.zainnasir.com/"
title: Zain Nasir
paginate: 7
theme: ["PaperMod"]

enableRobotsTXT: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: Zain Nasir
    description: "Software Developer & Researcher based in New York, currently searching for new grad positions."
    author: Zain Nasir
    DateFormat: "Jan 2, 2006"
    defaultTheme: dark
    disableThemeToggle: true

    ShowReadingTime: true
    ShowWordCount: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    ShowBreadCrumbs: false
    ShowPageNums: true
    hidemeta: false
    showtoc: true
    tocopen: false
    hideAuthor: true

    assets:
        favicon: "/favicon.ico"
        disableHLJS: false

    homeInfoParams:
        Title: "\U0001F44B Hi, welcome to my blog."
        Content: "I am a software developer and researcher with a Masters in Computer Science (AI Track) from Binghamton University, currently working at [Memorial Sloan Kettering Cancer Center](https://www.mskcc.org/). My expertise include DevOps, machine learning, and computer vision."
        Research: "My Masters [research](/research) involved optimizing edge-based SLAM techniques and tailoring them for deployment on small drones with limited compute power."
        #Contact: "I am searching for software development and machine learning engineer positions. If you have an opportunity for me, please reach out via [LinkedIn](https://www.linkedin.com/in/zainasir) or [Email](mailto:znasir1@Binghamton.edu)."
        Profile: "/profile.png"

    # Social Icons
    socialIconsStrokeWidth: 1.5
    socialIcons:
        - name: googlescholar
          url: "https://scholar.google.com/citations?user=OAVQtTsAAAAJ&hl=en&authuser=2"
        - name: researchgate
          url: "https://www.researchgate.net/profile/Zain-Ul-Abideen-Nasir?ev=hdr_xprf"
        - name: email
          url: "mailto:znasir1@binghamton.edu"
        - name: linkedin
          url: "https://www.linkedin.com/in/zainasir"
        - name: github
          url: "https://www.github.com/zainasir"

    # Search
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
        keys: ["title", "permalink", "summary", "content"]

    # Katex
    math: true

    # Hide meta description from blog. This doesn't remove description from SEO
    hideDescription: true

# Emoji
enableEmoji: true

# Navigation menu
menu:
    main:
        - name: Home
          url: /
          weight: 10
        - name: Blog
          pageRef: /blog
          weight: 20
        - name: Projects
          pageRef: /projects
          weight: 30
        - name: Research
          pageRef: /research
          weight: 40
        - name: Search
          pageRef: /search
          weight: 50

# Search
outputs:
    home:
        - HTML
        - RSS
        - JSON

# Disable default taxonomies
disableKinds:
    - taxonomy
